---
title: "create observation period table"
output: html_document
---


  
# Observation Period

```{sql connection=con}

select
observation_period_id, -- can this be an auto generated primary key?
patkey as person_id,
observation_period_start_date,
observation_period_end_date,
44814722 as period_type_concept_id -- concept for "Period while enrolled in insurance"

```




```{r}
tst <- tibble(
  patkey = c(rep(1,10), rep(2, 10)),
  month = c(c(1, 1, 2, 2:4, 1:4),   c(1, 3, 12, 2:4, 1:4)),
  year = c(rep(2015, 6), rep(2017, 4), rep(2015, 3), rep(2016, 7))
)

copy_to(con, tst)
```

```{r}
tst <- tbl(con, "##tst")
tst

```
```{sql connection=con}
SELECT patkey, month, year, sum(month) OVER (ORDER BY PATKEY ROWS UNBOUNDED PRECEDING) AS a FROM ##tst

```


```{r}
tst %>% 
  mutate(a = cumsum(month))
```

creation of observation periods from monthly eligibility records
```{r}

tst %>% 
  mutate(mon = (year - 2015)*12 + month) %>% 
  group_by(patkey) %>% 
  mutate(lag_mon = order_by(mon, lag(mon))) %>% 
  mutate(new_period = ifelse(is.na(lag_mon) | mon - lag_mon > 1, 1, 0)) %>% 
  mutate(period_id = order_by(mon, cumsum(new_period))) %>% 
  group_by(patkey, period_id) %>% 
  mutate(period_start = min(mon), period_end = max(mon)) %>% 
  select(-year, -month) %>% 
  ungroup() %>% 
  distinct(patkey, period_start, period_end) %>% show_query()

```


```{sql connection=con}
  SELECT patkey, month, year, (year - 2015)*12 + month AS timepoint
        FROM ##tst
```
```{sql connection=con}
  SELECT patkey, month, year, timepoint, LAG(timepoint, 1, NULL) OVER (PARTITION BY patkey ORDER BY timepoint) AS lag_timepoint
      FROM (
        -- create timepoint
        SELECT patkey, month, year, (year - 2015)*12 + month AS timepoint
        FROM ##tst
      ) timepoint

```


```{sql connection=con}

-- add period_start and period_end
SELECT patkey, month, year, timepoint, lag_timepoint, new_period_flag, period_id,
min(timepoint) OVER (PARTITION BY patkey, period_id) AS period_start, 
max(timepoint) OVER (PARTITION BY patkey, period_id) AS period_end
INTO ##tmp_obs_period
FROM (
  -- add period_id
  SELECT patkey, month, year, timepoint, lag_timepoint, new_period_flag,
    sum(new_period_flag) OVER (PARTITION BY patkey ORDER BY timepoint ROWS UNBOUNDED PRECEDING) AS period_id
  FROM (
    -- add new_period_flag
    SELECT patkey, month, year, timepoint, lag_timepoint, 
    CASE WHEN ((lag_timepoint IS NULL) OR timepoint - lag_timepoint > 1) THEN (1) ELSE (0) END AS new_period_flag
    FROM (
      -- add lag timepoint
      SELECT patkey, month, year, timepoint, 
        LAG(timepoint, 1, NULL) OVER (PARTITION BY patkey ORDER BY timepoint) AS lag_timepoint
      FROM (
        -- create timepoint
        SELECT patkey, month, year, (year - 2015)*12 + month - 1 AS timepoint -- timepoint needs to start counting at zero from reference month
        FROM ##tst
      ) timepoint
    ) lag_timepoint
  ) new_period_flag
) period_id





```


```{sql connection=con}
with intermediate as(
select distinct patkey, period_start, period_end, 
  cast(period_start as int) % 12 + 1 as month_start,  -- remainder after division by 12 where zero is mapped to 12
  floor(period_start/12) + 2015 as year_start,
  cast(period_end as int) % 12 + 1 as month_end,  -- remainder after division by 12 where zero is mapped to 12
  floor(period_end/12) + 2015 as year_end
from ##tmp_obs_period
)

select patkey, month_start, year_start, month_end, year_end,
DATEFROMPARTS(year_start, month_start, 1) as period_start,
EOMONTH(DATEFROMPARTS(year_end, month_end, 1), 0) as period_end
from intermediate

```


```{sql connection=con}

select distinct patkey, period_start, period_end from ##tmp_obs_period

```


```{sql connection=con}

SELECT patkey as person_id, 
  DATEFROMPARTS(year_start, month_start, 1) as observation_period_start_date,
  EOMONTH(DATEFROMPARTS(year_end, month_end, 1), 0) as observation_period_end_date,
  44814722 as period_type_concept_id

FROM (

SELECT DISTINCT
	add_start_and_end.patkey AS patkey
	,CAST(add_start_and_end.period_start AS INT) % 12 + 1 AS month_start
	,CAST(add_start_and_end.period_end AS INT) % 12 + 1 AS month_end
	,FLOOR(add_start_and_end.period_start/12) + 2015 AS year_start
	,FLOOR(add_start_and_end.period_end/12) + 2015 AS year_end

FROM	
	(SELECT
		add_period_id.patkey AS patkey
		,MIN(add_period_id.elig_period) OVER (PARTITION BY add_period_id.patkey, add_period_id.period_id) AS period_start
		,MAX(add_period_id.elig_period) OVER (PARTITION BY add_period_id.patkey, add_period_id.period_id) AS period_end
	FROM
		(SELECT
			add_period_flag.patkey AS patkey
			,add_period_flag.elig_period AS elig_period
			,SUM(add_period_flag.new_period_flag) OVER (PARTITION BY add_period_flag.patkey ORDER BY add_period_flag.elig_period ROWS UNBOUNDED PRECEDING) AS period_id
		FROM
			(SELECT
				lag_elig_periods.patkey AS patkey
				,lag_elig_periods.elig_period AS elig_period
				,lag_elig_periods.lag_elig_period AS lag_elig_period
				,CASE
					WHEN lag_elig_periods.lag_elig_period IS NULL OR lag_elig_periods.elig_period - lag_elig_periods.lag_elig_period > 1
						THEN 1
						ELSE 0
				END AS new_period_flag
			FROM	
				(SELECT
					elig_periods.patkey AS patkey
					,elig_periods.elig_period AS elig_period
					,LAG(elig_periods.elig_period, 1, NULL) OVER (PARTITION BY elig_periods.patkey ORDER BY elig_periods.elig_period) AS lag_elig_period

				FROM
					(SELECT 
						me.patkey AS patkey
						,(me.year - 2015)*12 + me.month - 1 AS elig_period

					FROM rch.me AS me
					) AS elig_periods
				) AS lag_elig_periods
			) AS add_period_flag
		) AS add_period_id
	) AS add_start_and_end
) AS add_month_year
ORDER BY person_id, observation_period_start_date

```

```{r}

# look up concept id for insurance

library(dplyr)
v <- tbl(con, dbplyr::in_schema("cdm", "vocabulary"))
v 
concept <- tbl(con, dbplyr::in_schema("cdm", "concept"))

concept %>% 
  filter(vocabulary_id == "Obs Period Type")

# Obs Period Type
  

```



