---
title: "Untitled"
output: html_document
---


Field	Required	Type	Description
location_id	Yes	integer	A unique identifier for each geographic location.
address_1	No	varchar(50)	The address field 1, typically used for the street address, as it appears in the source data.
address_2	No	varchar(50)	The address field 2, typically used for additional detail such as buildings, suites, floors, as it appears in the source data.
city	No	varchar(50)	The city field as it appears in the source data.
state	No	varchar(2)	The state field as it appears in the source data.
zip	No	varchar(9)	The zip or postal code.
county	No	varchar(20)	The county.
country	No	varchar(100)	The country
location_source_value	No	varchar(50)	The verbatim information that is used to uniquely identify the location as it appears in the source data.
latitude	No	float	The geocoded latitude
longitude	No	float	The geocoded longitude

```{r}
library(dplyr)
library(here)
zips <- readr::read_csv(here("DEV/RAW/USZIPS/uszips.csv"))
zips_db <- copy_to(con, zips, temporary = F, overwrite = T)

cities <- readr::read_csv(here("DEV/RAW/USCITIES/uscitiesv1.5.csv")) %>% 
  select(-15) # there is a problem with the zips field

cities_db <- copy_to(con, cities, temporary = F, overwrite = T)

```


```{sql connection=con}
select * from cities

```






